# Прослушивание TLS на порту 5671
listeners.ssl.default = 5671

# Пути к сертификатам (внутри контейнера)
ssl_options.cacertfile = /etc/pki/tls/CACert.pem
ssl_options.certfile   = /etc/pki/tls/ServerCert.pem
ssl_options.keyfile    = /etc/pki/tls/ServerKey.pem

# Настройка TLS для админки (Management UI)
management.ssl.cacertfile = /etc/pki/tls/CACert.pem
management.ssl.certfile   = /etc/pki/tls/ServerCert.pem
management.ssl.keyfile    = /etc/pki/tls/ServerKey.pem


# Включение проверки клиентских сертификатов
ssl_options.verify = verify_peer
ssl_options.fail_if_no_peer_cert = true

# Механизмы аутентификации
auth_mechanisms.1 = EXTERNAL
auth_mechanisms.2 = BASIC

# Откуда брать логин
ssl_cert_login_from = common_name
